language: python
python:
  - "3.6"


script: ./test.py $TEST_SUITE

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - make asn1
  - make dev-install
script:
  - make test
