language: python
python:
  - "3.6"
  - "3.5"


script: ./test.py $TEST_SUITE

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - make dev-install
script:
  - make test
